name = "usrahmedic-cms"
compatibility_date = "2026-05-01"
pages_build_output_dir = "apps/platform/out"

[vars]
APP_ENV = "production"
PUBLIC_APP_NAME = "UsrahMedic"
ALLOWED_ORIGINS = "https://usrahmedic-cms.pages.dev"

[[d1_databases]]
binding = "USRAHMEDIC_DB"
database_name = "usrahmedic-cms"
database_id = "a898fe29-d388-4e98-96dc-728d95f98f9c"
preview_database_id = "2dd41a9b-2c39-46c0-aa7a-7e2e7aaf8288"
migrations_dir = "migrations"
migrations_table = "d1_migrations"
